/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<T & {
  _key: string;
}>;

// Source: schema.json
export type StatusNote = {
  _type: "statusNote";
  label?: string;
  detail?: string;
};

export type SessionBand = {
  _type: "sessionBand";
  day?: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
  time?: string;
  note?: string;
};

export type LinkItem = {
  _type: "linkItem";
  name?: string;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
  _key: string;
}>;

export type ResourceLinkGroup = {
  _id: string;
  _type: "resourceLinkGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  order?: number;
  items?: Array<{
    _key: string;
  } & LinkItem>;
};

export type ResourceGroupReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "resourceGroup";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  group?: ResourceGroupReference;
  kind?: "PDF" | "Online form" | "Web page";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  url?: string;
  note?: string;
  order?: number;
};

export type ResourceGroup = {
  _id: string;
  _type: "resourceGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type FaqCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqCategory";
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  category?: FaqCategoryReference;
  featuredOnLanding?: boolean;
  order?: number;
};

export type FaqCategory = {
  _id: string;
  _type: "faqCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: CategoryReference;
  brief?: string;
  authors?: Array<{
    _key: string;
  } & PersonReference>;
  publishedAt?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type AgeGroup = {
  _id: string;
  _type: "ageGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  ages?: string;
  min?: number;
  max?: number;
  focus?: string;
  order?: number;
};

export type AgeGroupReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "ageGroup";
};

export type BranchReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "branch";
};

export type Programme = {
  _id: string;
  _type: "programme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tag?: string;
  agesLabel?: string;
  summary?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  detailsHeading?: string;
  details?: Array<string>;
  ageRange?: {
    min?: number;
    max?: number;
  };
  ageGroups?: Array<{
    _key: string;
  } & AgeGroupReference>;
  branches?: Array<{
    _key: string;
  } & BranchReference>;
  season?: string;
  ref?: string;
  order?: number;
  flagship?: boolean;
  bookingKey?: "mini_kickers" | "pre_academy" | "foundation" | "youth_development" | "weekend_morning" | "trial" | "seniors" | "competitive";
};

export type ProgrammeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "programme";
};

export type Branch = {
  _id: string;
  _type: "branch";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  shortName?: string;
  slug?: Slug;
  address?: string;
  about?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  programmes?: ArrayOf<AgeGroupReference | ProgrammeReference>;
  status?: StatusNote;
  sessions?: Array<{
    _key: string;
  } & SessionBand>;
  coaches?: Array<{
    _key: string;
  } & PersonReference>;
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  shortName?: string;
  parent?: string;
  email?: string;
  absenceLine?: string;
  whatsappNumber?: string;
  instagram?: {
    handle?: string;
    url?: string;
  };
  bookingPortal?: {
    label?: string;
    url?: string;
    programmes?: string;
  };
  safeguarding?: {
    designatedSafeguardingLead?: PersonReference;
    clubWelfareOfficer?: PersonReference;
    welfareEmail?: string;
    welfarePhone?: string;
  };
  leaguesContact?: {
    person?: PersonReference;
    email?: string;
  };
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  kind?: "leadership" | "coach";
  role?: string;
  alsoRole?: string;
  description?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = StatusNote | SessionBand | LinkItem | SanityImageAssetReference | BlockContent | ResourceLinkGroup | ResourceGroupReference | SanityFileAssetReference | Resource | ResourceGroup | Slug | FaqCategoryReference | Faq | FaqCategory | CategoryReference | PersonReference | Post | SanityImageCrop | SanityImageHotspot | Category | AgeGroup | AgeGroupReference | BranchReference | Programme | ProgrammeReference | Branch | SiteSettings | Person | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    name,    shortName,    parent,    email,    absenceLine,    whatsappNumber,    instagram{handle, url},    bookingPortal{label, url, programmes},    safeguarding{      "designatedSafeguardingLead": designatedSafeguardingLead->{name, role},      "clubWelfareOfficer": clubWelfareOfficer->{name, role},      welfareEmail,      welfarePhone    },    leaguesContact{      "name": person->name,      "role": person->role,      email    }  }
export type SETTINGS_QUERY_RESULT = {
  name: string | null;
  shortName: string | null;
  parent: string | null;
  email: string | null;
  absenceLine: string | null;
  whatsappNumber: string | null;
  instagram: {
    handle: string | null;
    url: string | null;
  } | null;
  bookingPortal: {
    label: string | null;
    url: string | null;
    programmes: string | null;
  } | null;
  safeguarding: {
    designatedSafeguardingLead: {
      name: string | null;
      role: string | null;
    } | null;
    clubWelfareOfficer: {
      name: string | null;
      role: string | null;
    } | null;
    welfareEmail: string | null;
    welfarePhone: string | null;
  } | null;
  leaguesContact: {
    name: string | null;
    role: string | null;
    email: string | null;
  } | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: BRANCHES_QUERY
// Query: *[_type == "branch"] | order(order asc){    "slug": slug.current,    name,    shortName,    address,    about,    status{label, detail},    image,    gallery[],    "programmes": programmes[]->{_type, name, ages},    "coaches": coaches[]->{name, role, alsoRole, description, photo},    "sessions": sessions[]{day, time, note}  }
export type BRANCHES_QUERY_RESULT = Array<{
  slug: string | null;
  name: string | null;
  shortName: string | null;
  address: string | null;
  about: string | null;
  status: {
    label: string | null;
    detail: string | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  programmes: Array<{
    _type: "ageGroup";
    name: string | null;
    ages: string | null;
  } | {
    _type: "programme";
    name: string | null;
    ages: null;
  }> | null;
  coaches: Array<{
    name: string | null;
    role: string | null;
    alsoRole: string | null;
    description: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
  sessions: Array<{
    day: "Friday" | "Monday" | "Saturday" | "Sunday" | "Thursday" | "Tuesday" | "Wednesday" | null;
    time: string | null;
    note: string | null;
  }> | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: PROGRAMMES_QUERY
// Query: *[_type == "programme"] | order(order asc){    "slug": slug.current,    ref,    name,    tag,    agesLabel,    summary,    description,    detailsHeading,    details,    ageRange{min, max},    season,    flagship,    bookingKey,    image,    body,    "ageGroups": ageGroups[]->{name, ages, min, max, focus},    "branchSlugs": branches[]->slug.current  }
export type PROGRAMMES_QUERY_RESULT = Array<{
  slug: string | null;
  ref: string | null;
  name: string | null;
  tag: string | null;
  agesLabel: string | null;
  summary: string | null;
  description: string | null;
  detailsHeading: string | null;
  details: Array<string> | null;
  ageRange: {
    min: number | null;
    max: number | null;
  } | null;
  season: string | null;
  flagship: boolean | null;
  bookingKey: "competitive" | "foundation" | "mini_kickers" | "pre_academy" | "seniors" | "trial" | "weekend_morning" | "youth_development" | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
  ageGroups: Array<{
    name: string | null;
    ages: string | null;
    min: number | null;
    max: number | null;
    focus: string | null;
  }> | null;
  branchSlugs: Array<string | null> | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: PATHWAY_QUERY
// Query: *[_type == "ageGroup" && inPathway == true] | order(order asc){    name,    ages,    min,    max,    focus  }
export type PATHWAY_QUERY_RESULT = Array<never>;

// Source: ../src/sanity/queries.ts
// Variable: LEADERSHIP_QUERY
// Query: *[_type == "person" && kind == "leadership"] | order(order asc){    name,    role,    alsoRole,    description,    photo  }
export type LEADERSHIP_QUERY_RESULT = Array<{
  name: string | null;
  role: string | null;
  alsoRole: string | null;
  description: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post"] | order(order asc){    "slug": slug.current,    title,    "category": category->title,    brief,    "byline": array::join(authors[]->name, " & "),    publishedAt,    heroImage,    body  }
export type POSTS_QUERY_RESULT = Array<{
  slug: string | null;
  title: string | null;
  category: string | null;
  brief: string | null;
  byline: string | null;
  publishedAt: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: FAQ_CATEGORIES_QUERY
// Query: *[_type == "faqCategory"] | order(order asc){    "id": slug.current,    title,    "questions": *[_type == "faq" && category._ref == ^._id] | order(order asc){      question,      answer,      featuredOnLanding,      landingOrder    }  }
export type FAQ_CATEGORIES_QUERY_RESULT = Array<{
  id: string | null;
  title: string | null;
  questions: Array<{
    question: string | null;
    answer: string | null;
    featuredOnLanding: boolean | null;
    landingOrder: null;
  }>;
}>;

// Source: ../src/sanity/queries.ts
// Variable: RESOURCE_GROUPS_QUERY
// Query: *[_type == "resourceGroup"] | order(order asc){    "id": slug.current,    title,    description,    "items": *[_type == "resource" && group._ref == ^._id] | order(order asc){      name,      kind,      note,      url,      "file": file.asset->{url, size}    }  }
export type RESOURCE_GROUPS_QUERY_RESULT = Array<{
  id: string | null;
  title: string | null;
  description: string | null;
  items: Array<{
    name: string | null;
    kind: "Online form" | "PDF" | "Web page" | null;
    note: string | null;
    url: string | null;
    file: {
      url: string | null;
      size: number | null;
    } | null;
  }>;
}>;

// Source: ../src/sanity/queries.ts
// Variable: RESOURCE_LINKS_QUERY
// Query: *[_type == "resourceLinkGroup"] | order(order asc){    title,    "items": items[]{name, url}  }
export type RESOURCE_LINKS_QUERY_RESULT = Array<{
  title: string | null;
  items: Array<{
    name: string | null;
    url: string | null;
  }> | null;
}>;

